name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v2
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          keep_history: true
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
