name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # - id: nvmrc
    #   uses: browniebroke/read-nvmrc-action@v1
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: '${{ steps.nvmrc.outputs.node_version }}'
      
    # - name: Yarn Setup
    #   uses: DerYeger/yarn-setup-action@v1.0.1

    # - name: Build
    #   run: yarn build
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        keep_history: true
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
